execute pathogen#infect()

syntax on
filetype plugin indent on

:set number
:set hlsearch

:set modeline
:set ls=2

:set expandtab
:set tabstop=4
:set shiftwidth=4

autocmd FileType gitcommit set textwidth=72 fo=croqt

" set t_Co=256

" Solarized stuff
" let g:solarized_termcolors=256
" let g:solarized_termtrans=1
set background=dark
colorscheme solarized

" NERDTree toggle
map <C-n> :NERDTreeFind <CR>
"autocmd BufEnter * silent! if bufname('%') !~# 'NERD_tree_' | cd %:p:h | NERDTreeFind | wincmd p | endif


highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" don't overwrite yank buffer when pressing del
nnoremap <Del> "_x
" no more ex mode
map Q <Nop>

" Tab autocompletion
set wildmode=longest,list,full
set wildmenu

highlight clear SignColumn

set noshowmode
let g:lightline = {
            \ 'colorscheme': 'wombat',
            \ 'active': {
            \   'left': [ [ 'mode', 'paste' ],
            \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ]
            \ },
            \ 'component': {
            \   'readonly': '%{&filetype=="help"?"":&readonly?"⭤":""}',
            \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}',
            \   'fugitive': '%{exists("*fugitive#head")?fugitive#head():""}'
            \ },
            \ 'component_visible_condition': {
            \   'readonly': '(&filetype!="help"&& &readonly)',
            \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))',
            \   'fugitive': '(exists("*fugitive#head") && ""!=fugitive#head())'
            \ },
            \ 'separator': { 'left': '|', 'right': '|' },
            \ 'subseparator': { 'left': '|', 'right': '|' }
            \ }
